# Generated by Django 5.0.6 on 2024-08-24 03:02

import django.db.models.deletion
import image.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "canvasobj_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.canvasobj",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=image.models.get_em_image_upload_path),
                ),
                (
                    "dzi_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=image.models.get_dzi_image_upload_path,
                    ),
                ),
                ("friendly_name", models.CharField(max_length=255)),
                (
                    "canvas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.canvas",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.canvasobj",),
        ),
    ]
