# Generated by Django 5.0.6 on 2024-08-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="friendly_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
