# Generated by Django 5.0.6 on 2025-10-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0002_alter_image_friendly_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="view_status",
            field=models.IntegerField(
                choices=[
                    (0, "No File"),
                    (1, "Unprocessed"),
                    (2, "Processing"),
                    (3, "Ready"),
                ],
                default=1,
            ),
        ),
    ]
