# Generated by Django 5.0.6 on 2024-08-24 03:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Canvas",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("pixel_size_nm", models.FloatField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CanvasObj",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("flip", models.BooleanField(default=False)),
                ("rotation_degrees", models.IntegerField(null=True)),
                ("canvas_x", models.IntegerField(null=True)),
                ("canvas_y", models.IntegerField(null=True)),
                ("pixel_size_nm", models.FloatField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
