# Generated by Django 5.0.6 on 2024-12-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_canvas_height_alter_canvas_width"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="canvasobj",
            name="canvas_x",
        ),
        migrations.RemoveField(
            model_name="canvasobj",
            name="canvas_y",
        ),
        migrations.AddField(
            model_name="canvasobj",
            name="canvas_bbox",
            field=models.JSONField(
                help_text="Array of 4 [x,y] coordinates defining bounding box",
                null=True,
            ),
        ),
    ]
