# Generated by Django 5.0.6 on 2025-06-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_canvasobj_canvas_x_remove_canvasobj_canvas_y_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="canvas",
            name="shape",
            field=models.JSONField(null=True),
        ),
    ]
