/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as MimsimageMimsImageSetIdImport } from './routes/mims_image/$mimsImageSetId'
import { Route as MimsimageMimsImageIdImport } from './routes/mims_image/$mimsImageId'
import { Route as CanvasCanvasIdIndexImport } from './routes/canvas/$canvasId/index'
import { Route as CanvasCanvasIdMimsImageSetMimsImageSetIdImport } from './routes/canvas/$canvasId/mimsImageSet/$mimsImageSetId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MimsimageMimsImageSetIdRoute = MimsimageMimsImageSetIdImport.update({
  path: '/mims_image/$mimsImageSetId',
  getParentRoute: () => rootRoute,
} as any)

const MimsimageMimsImageIdRoute = MimsimageMimsImageIdImport.update({
  path: '/mims_image/$mimsImageId',
  getParentRoute: () => rootRoute,
} as any)

const CanvasCanvasIdIndexRoute = CanvasCanvasIdIndexImport.update({
  path: '/canvas/$canvasId/',
  getParentRoute: () => rootRoute,
} as any)

const CanvasCanvasIdMimsImageSetMimsImageSetIdRoute =
  CanvasCanvasIdMimsImageSetMimsImageSetIdImport.update({
    path: '/canvas/$canvasId/mimsImageSet/$mimsImageSetId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/mims_image/$mimsImageId': {
      id: '/mims_image/$mimsImageId'
      path: '/mims_image/$mimsImageId'
      fullPath: '/mims_image/$mimsImageId'
      preLoaderRoute: typeof MimsimageMimsImageIdImport
      parentRoute: typeof rootRoute
    }
    '/mims_image/$mimsImageSetId': {
      id: '/mims_image/$mimsImageSetId'
      path: '/mims_image/$mimsImageSetId'
      fullPath: '/mims_image/$mimsImageSetId'
      preLoaderRoute: typeof MimsimageMimsImageSetIdImport
      parentRoute: typeof rootRoute
    }
    '/canvas/$canvasId/': {
      id: '/canvas/$canvasId/'
      path: '/canvas/$canvasId'
      fullPath: '/canvas/$canvasId'
      preLoaderRoute: typeof CanvasCanvasIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/canvas/$canvasId/mimsImageSet/$mimsImageSetId': {
      id: '/canvas/$canvasId/mimsImageSet/$mimsImageSetId'
      path: '/canvas/$canvasId/mimsImageSet/$mimsImageSetId'
      fullPath: '/canvas/$canvasId/mimsImageSet/$mimsImageSetId'
      preLoaderRoute: typeof CanvasCanvasIdMimsImageSetMimsImageSetIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  MimsimageMimsImageIdRoute,
  MimsimageMimsImageSetIdRoute,
  CanvasCanvasIdIndexRoute,
  CanvasCanvasIdMimsImageSetMimsImageSetIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/mims_image/$mimsImageId",
        "/mims_image/$mimsImageSetId",
        "/canvas/$canvasId/",
        "/canvas/$canvasId/mimsImageSet/$mimsImageSetId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/mims_image/$mimsImageId": {
      "filePath": "mims_image/$mimsImageId.tsx"
    },
    "/mims_image/$mimsImageSetId": {
      "filePath": "mims_image/$mimsImageSetId.tsx"
    },
    "/canvas/$canvasId/": {
      "filePath": "canvas/$canvasId/index.tsx"
    },
    "/canvas/$canvasId/mimsImageSet/$mimsImageSetId": {
      "filePath": "canvas/$canvasId/mimsImageSet/$mimsImageSetId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
