/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as MimsimageMimsImageIdImport } from './routes/mims_image/$mimsImageId'
import { Route as EmimageEmImageIdImport } from './routes/em_image/$emImageId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MimsimageMimsImageIdRoute = MimsimageMimsImageIdImport.update({
  path: '/mims_image/$mimsImageId',
  getParentRoute: () => rootRoute,
} as any)

const EmimageEmImageIdRoute = EmimageEmImageIdImport.update({
  path: '/em_image/$emImageId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/em_image/$emImageId': {
      id: '/em_image/$emImageId'
      path: '/em_image/$emImageId'
      fullPath: '/em_image/$emImageId'
      preLoaderRoute: typeof EmimageEmImageIdImport
      parentRoute: typeof rootRoute
    }
    '/mims_image/$mimsImageId': {
      id: '/mims_image/$mimsImageId'
      path: '/mims_image/$mimsImageId'
      fullPath: '/mims_image/$mimsImageId'
      preLoaderRoute: typeof MimsimageMimsImageIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  EmimageEmImageIdRoute,
  MimsimageMimsImageIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/em_image/$emImageId",
        "/mims_image/$mimsImageId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/em_image/$emImageId": {
      "filePath": "em_image/$emImageId.tsx"
    },
    "/mims_image/$mimsImageId": {
      "filePath": "mims_image/$mimsImageId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
