# Generated by Django 5.0.6 on 2024-08-24 03:02

import django.db.models.deletion
import mims.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Isotope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MIMSImage",
            fields=[
                (
                    "canvasobj_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.canvasobj",
                    ),
                ),
                ("status", models.CharField(default="PREPROCESSING", max_length=50)),
                (
                    "file",
                    models.FileField(upload_to=mims.models.get_mims_image_upload_path),
                ),
                (
                    "canvas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mims",
                        to="core.canvas",
                    ),
                ),
                ("isotopes", models.ManyToManyField(to="mims.isotope")),
            ],
            options={
                "abstract": False,
            },
            bases=("core.canvasobj",),
        ),
        migrations.CreateModel(
            name="MIMSAlignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("status", models.CharField(default="ESTIMATE_INITIAL", max_length=50)),
                ("x_offset", models.IntegerField()),
                ("y_offset", models.IntegerField()),
                ("rotation_degrees", models.IntegerField()),
                ("flip_hor", models.BooleanField()),
                ("scale", models.FloatField()),
                (
                    "mims_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alignments",
                        to="mims.mimsimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MIMSImageSet",
            fields=[
                (
                    "canvasobj_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.canvasobj",
                    ),
                ),
                (
                    "canvas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mims_sets",
                        to="core.canvas",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.canvasobj",),
        ),
        migrations.AddField(
            model_name="mimsimage",
            name="image_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mims_images",
                to="mims.mimsimageset",
            ),
        ),
    ]
