# Generated by Django 5.0.6 on 2024-10-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mimsalignment",
            name="info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
