# Generated by Django 5.0.6 on 2024-06-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mimsimageset",
            name="isotopes",
        ),
        migrations.AddField(
            model_name="mimsimage",
            name="isotopes",
            field=models.ManyToManyField(to="mims.isotope"),
        ),
    ]
