# Generated by Django 5.0.6 on 2024-10-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0002_mimsalignment_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="mimsimageset",
            name="status",
            field=models.CharField(default="PREPROCESSING", max_length=50),
        ),
    ]
