# Generated by Django 5.0.6 on 2024-06-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0003_mimsimage_status_alter_mimsimage_pixel_size_nm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mimsimage",
            name="flipped",
        ),
        migrations.RemoveField(
            model_name="mimsimage",
            name="rotation_degrees",
        ),
    ]
