# Generated by Django 5.0.6 on 2025-02-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0003_mimsimageset_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mimsimage",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
