# Generated by Django 5.0.6 on 2025-02-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0004_mimsimage_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="mimsimage",
            name="image_set_priority",
            field=models.IntegerField(default=0),
        ),
    ]
