# Generated by Django 5.0.6 on 2024-06-21 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0004_remove_mimsimage_flipped_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MIMSAlignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("status", models.CharField(default="ESTIMATE_INITIAL", max_length=50)),
                ("x_offset", models.IntegerField()),
                ("y_offset", models.IntegerField()),
                ("rotation_degrees", models.IntegerField()),
                ("flip", models.BooleanField()),
                ("scale", models.FloatField()),
                (
                    "mims_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alignments",
                        to="mims.mimsimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
