# Generated by Django 5.0.6 on 2025-03-30 13:17

import django.db.models.deletion
import mims.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0005_mimsimage_image_set_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="MimsTiffImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "image",
                    models.FileField(upload_to=mims.models.get_mims_image_upload_path),
                ),
                ("name", models.CharField(default="", max_length=50)),
                (
                    "mims_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mims_tiff_images",
                        to="mims.mimsimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
