# Generated by Django 5.0.6 on 2024-06-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0005_mimsalignment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mimsalignment",
            old_name="flip",
            new_name="flip_hor",
        ),
    ]
