# Generated by Django 5.0.6 on 2025-03-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0006_mimstiffimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="mimsimage",
            name="transform",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
