# Generated by Django 5.0.6 on 2024-08-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0006_rename_flip_mimsalignment_flip_hor"),
    ]

    operations = [
        migrations.AddField(
            model_name="mimsimageset",
            name="composite_mims_image",
            field=models.FileField(null=True, upload_to="mims_images/"),
        ),
    ]
