# Generated by Django 5.0.6 on 2024-08-12 13:14

import mims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0007_mimsimageset_composite_mims_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mimsimageset",
            name="composite_mims_image",
        ),
        migrations.AlterField(
            model_name="mimsimage",
            name="file",
            field=models.FileField(upload_to=mims.models.get_mims_image_upload_path),
        ),
    ]
