# Generated by Django 5.0.6 on 2025-03-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0007_mimsimage_transform"),
    ]

    operations = [
        migrations.AddField(
            model_name="mimstiffimage",
            name="registration_bbox",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
