# Generated by Django 5.0.6 on 2025-05-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0008_mimstiffimage_registration_bbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="mimsimage",
            name="affine_tform",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mimsimage",
            name="reg_points",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
