# Generated by Django 5.0.6 on 2024-08-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0008_remove_mimsimageset_composite_mims_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mimsimageset",
            name="em_coordinates_x",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mimsimageset",
            name="em_coordinates_y",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mimsimageset",
            name="em_scale",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="mimsimageset",
            name="flip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mimsimageset",
            name="rotation_degrees",
            field=models.IntegerField(null=True),
        ),
    ]
