# Generated by Django 5.0.6 on 2025-06-19 21:50

import mims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0009_mimsimage_affine_tform_mimsimage_reg_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mimsimage",
            name="affine_tform",
        ),
        migrations.RemoveField(
            model_name="mimsimage",
            name="reg_points",
        ),
        migrations.AlterField(
            model_name="mimstiffimage",
            name="image",
            field=models.FileField(
                upload_to=mims.models.get_mims_tiff_image_upload_path
            ),
        ),
    ]
