# Generated by Django 5.0.6 on 2025-06-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0010_remove_mimsimage_affine_tform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mimsimage",
            name="registration_info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
