# Generated by Django 5.0.6 on 2025-07-01 19:51

import django.db.models.deletion
import mims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_canvas_shape"),
        ("mims", "0011_mimsimage_registration_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="MIMSOverlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mosaic",
                    models.FileField(upload_to=mims.models.get_mosaic_upload_path),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["isotope"],
            },
        ),
        migrations.AlterModelOptions(
            name="mimsimageset",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="mimsimageset",
            name="mask",
            field=models.FileField(blank=True, null=True, upload_to="mims_masks/"),
        ),
        migrations.AddIndex(
            model_name="mimsimageset",
            index=models.Index(
                fields=["canvas"], name="mims_mimsim_canvas__debb12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mimsimageset",
            index=models.Index(fields=["status"], name="mims_mimsim_status_aca595_idx"),
        ),
        migrations.AddField(
            model_name="mimsoverlay",
            name="image_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overlays",
                to="mims.mimsimageset",
            ),
        ),
        migrations.AddField(
            model_name="mimsoverlay",
            name="isotope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overlays",
                to="mims.isotope",
            ),
        ),
        migrations.AddIndex(
            model_name="mimsoverlay",
            index=models.Index(
                fields=["image_set"], name="mims_mimsov_image_s_2832bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mimsoverlay",
            index=models.Index(
                fields=["isotope"], name="mims_mimsov_isotope_bee5e3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mimsoverlay",
            unique_together={("image_set", "isotope")},
        ),
    ]
