# Generated by Django 5.0.6 on 2025-07-02 15:23

import mims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0012_mimsoverlay_alter_mimsimageset_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mimsimageset",
            name="mask",
            field=models.FileField(
                blank=True, null=True, upload_to=mims.models.get_mask_upload_path
            ),
        ),
    ]
