# Generated by Django 5.0.6 on 2025-09-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0013_alter_mimsimageset_mask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mimsoverlay",
            name="mosaic",
            field=models.CharField(
                help_text="Path to DZI file relative to MEDIA_ROOT", max_length=500
            ),
        ),
    ]
