# Generated by Django 5.0.6 on 2025-09-01 03:56

from django.db import migrations, models


def set_existing_status_to_registered(apps, schema_editor):
    """Set all existing MIMSImageSet records to 'registered' status"""
    MIMSImageSet = apps.get_model("mims", "MIMSImageSet")
    # Use the enum string value 'registered'
    MIMSImageSet.objects.all().update(status="registered")


def reverse_set_existing_status_to_registered(apps, schema_editor):
    """Reverse operation - set all records back to 'PREPROCESSING'"""
    MIMSImageSet = apps.get_model("mims", "MIMSImageSet")
    MIMSImageSet.objects.all().update(status="PREPROCESSING")


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0014_alter_mimsoverlay_mosaic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mimsimageset",
            name="status",
            field=models.CharField(
                choices=[
                    ("preprocessing", "Preprocessing"),
                    ("preprocessed", "Preprocessed"),
                    ("partially_registered", "Partially Registered"),
                    ("registered", "Registered"),
                ],
                default="preprocessing",
                max_length=50,
            ),
        ),
        migrations.RunPython(
            set_existing_status_to_registered,
            reverse_set_existing_status_to_registered,
        ),
    ]
