# Generated by Django 5.0.6 on 2025-09-01 04:04

from django.db import migrations, models


def set_existing_mimsimage_status_to_registered(apps, schema_editor):
    """Set all existing MIMSImage records to 'registered' status"""
    MIMSImage = apps.get_model("mims", "MIMSImage")
    MIMSImage.objects.all().update(status="registered")


def reverse_set_existing_mimsimage_status_to_registered(apps, schema_editor):
    """Reverse operation - set all records back to old status values"""
    MIMSImage = apps.get_model("mims", "MIMSImage")
    MIMSImage.objects.all().update(status="PREPROCESSING")


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0015_alter_mimsimageset_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mimsimage",
            name="status",
            field=models.CharField(
                choices=[
                    ("preprocessing", "Preprocessing"),
                    ("preprocessed", "Preprocessed"),
                    ("registering", "Registering"),
                    ("registered", "Registered"),
                ],
                default="preprocessing",
                max_length=50,
            ),
        ),
        migrations.RunPython(
            set_existing_mimsimage_status_to_registered,
            reverse_set_existing_mimsimage_status_to_registered,
        ),
    ]
