# Generated by Django 5.0.6 on 2025-09-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0016_alter_mimsimage_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mimsimage",
            name="status",
            field=models.CharField(
                choices=[
                    ("preprocessing", "Preprocessing"),
                    ("preprocessed", "Preprocessed"),
                    ("registering", "Registering"),
                    ("registered", "Registered"),
                    ("invalid_file", "Invalid File"),
                    ("outside_canvas", "Outside Canvas"),
                ],
                default="preprocessing",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mimsimageset",
            name="status",
            field=models.CharField(
                choices=[
                    ("preprocessing", "Preprocessing"),
                    ("preprocessed", "Preprocessed"),
                    ("rough_alignment", "Rough Alignment"),
                    ("partially_registered", "Partially Registered"),
                    ("registered", "Registered"),
                ],
                default="preprocessing",
                max_length=50,
            ),
        ),
    ]
