# Generated by Django 5.0.6 on 2025-11-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mims", "0017_alter_mimsimage_status_alter_mimsimageset_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mimsimageset",
            name="mask",
        ),
    ]
