# Generated by Django 5.0.6 on 2025-09-02 02:59

import django.db.models.deletion
import segmentations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_canvas_shape"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentationFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "file",
                    models.FileField(),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Type of segmentation (e.g., 'mitochondria', 'cells')",
                        max_length=100,
                    ),
                ),
                (
                    "upload_type",
                    models.CharField(
                        choices=[
                            ("probability", "Probability Map"),
                            ("label", "Label Map"),
                        ],
                        default="probability",
                        max_length=20,
                    ),
                ),
                (
                    "threshold",
                    models.FloatField(
                        blank=True,
                        help_text="Threshold value for probability maps (0-1)",
                        null=True,
                    ),
                ),
                (
                    "min_area",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum area for objects after hole filling (in pixels)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                ("processing_info", models.JSONField(blank=True, null=True)),
                (
                    "canvas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segmentation_files",
                        to="core.canvas",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CanvasSegmentedObj",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Object type (e.g., 'mitochondria', 'cell')",
                        max_length=100,
                    ),
                ),
                (
                    "polygon",
                    models.JSONField(
                        help_text="List of [x, y] coordinate pairs defining the object boundary"
                    ),
                ),
                ("area", models.FloatField(help_text="Area of the object in pixels")),
                (
                    "label_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Original label ID from label map",
                        null=True,
                    ),
                ),
                (
                    "centroid",
                    models.JSONField(
                        blank=True,
                        help_text="[x, y] coordinates of object centroid",
                        null=True,
                    ),
                ),
                (
                    "bbox",
                    models.JSONField(
                        blank=True,
                        help_text="Bounding box as [min_x, min_y, max_x, max_y]",
                        null=True,
                    ),
                ),
                (
                    "canvas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segmented_objects",
                        to="core.canvas",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent object (e.g., cell containing this organelle)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="segmentations.canvassegmentedobj",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objects",
                        to="segmentations.segmentationfile",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "-area"],
            },
        ),
        migrations.AddIndex(
            model_name="segmentationfile",
            index=models.Index(
                fields=["canvas"], name="segmentatio_canvas__95f93d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="segmentationfile",
            index=models.Index(fields=["status"], name="segmentatio_status_e842ee_idx"),
        ),
        migrations.AddIndex(
            model_name="canvassegmentedobj",
            index=models.Index(
                fields=["canvas"], name="segmentatio_canvas__ecbaae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="canvassegmentedobj",
            index=models.Index(
                fields=["source_file"], name="segmentatio_source__b4c8ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="canvassegmentedobj",
            index=models.Index(fields=["name"], name="segmentatio_name_43b12e_idx"),
        ),
        migrations.AddIndex(
            model_name="canvassegmentedobj",
            index=models.Index(
                fields=["parent"], name="segmentatio_parent__e9c564_idx"
            ),
        ),
    ]
