# Generated by Django 5.0.6 on 2025-09-02 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("segmentations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentationfile",
            name="progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="segmentationfile",
            name="progress_message",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="canvassegmentedobj",
            name="source_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="segmented_objects",
                to="segmentations.segmentationfile",
            ),
        ),
    ]
