# Generated by Django 5.0.6 on 2025-11-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("segmentations", "0002_segmentationfile_progress_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="segmentationfile",
            name="file",
        ),
    ]
