# Generated by Django 5.0.6 on 2025-11-06 21:21

import segmentations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("segmentations", "0003_remove_segmentationfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentationfile",
            name="dzi_file",
            field=models.FileField(
                blank=True,
                help_text="DZI info.json file for viewing",
                null=True,
                upload_to=segmentations.models.get_segmentation_dzi_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="segmentationfile",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Segmentation file (compressed PNG)",
                null=True,
                upload_to=segmentations.models.get_segmentation_compressed_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="segmentationfile",
            name="raw_file",
            field=models.FileField(
                default="bla.txt",
                help_text="Raw uploaded segmentation file (TIFF or PNG)",
                upload_to=segmentations.models.get_segmentation_raw_upload_path,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="segmentationfile",
            name="sam2_dzi_file",
            field=models.FileField(
                blank=True,
                help_text="DZI info.json file for SAM2 segmentation",
                null=True,
                upload_to=segmentations.models.get_segmentation_dzi_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="segmentationfile",
            name="sobel_dzi_file",
            field=models.FileField(
                blank=True,
                help_text="DZI info.json file for Sobel edge detection",
                null=True,
                upload_to=segmentations.models.get_segmentation_dzi_upload_path,
            ),
        ),
    ]
