# Generated by Django 5.0.6 on 2025-11-06 22:00

import segmentations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "segmentations",
            "0004_segmentationfile_dzi_file_segmentationfile_file_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="segmentationfile",
            name="dzi_file",
            field=models.FileField(
                blank=True,
                help_text="DZI info.json file for viewing",
                max_length=500,
                null=True,
                upload_to=segmentations.models.get_segmentation_dzi_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="segmentationfile",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Segmentation file (compressed PNG)",
                max_length=500,
                null=True,
                upload_to=segmentations.models.get_segmentation_compressed_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="segmentationfile",
            name="raw_file",
            field=models.FileField(
                help_text="Raw uploaded segmentation file (TIFF or PNG) - deleted after processing",
                max_length=500,
                upload_to=segmentations.models.get_segmentation_raw_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="segmentationfile",
            name="sam2_dzi_file",
            field=models.FileField(
                blank=True,
                help_text="DZI info.json file for SAM2 segmentation",
                max_length=500,
                null=True,
                upload_to=segmentations.models.get_segmentation_dzi_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="segmentationfile",
            name="sobel_dzi_file",
            field=models.FileField(
                blank=True,
                help_text="DZI info.json file for Sobel edge detection",
                max_length=500,
                null=True,
                upload_to=segmentations.models.get_segmentation_dzi_upload_path,
            ),
        ),
    ]
