# Generated by Django 5.0.6 on 2024-06-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emimage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emimage",
            name="converted_file",
            field=models.ImageField(
                blank=True, null=True, upload_to="mims_images/converted/"
            ),
        ),
    ]
