# Generated by Django 5.0.6 on 2024-06-18 13:08

import emimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emimage", "0002_emimage_converted_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emimage",
            name="converted_file",
        ),
        migrations.AddField(
            model_name="emimage",
            name="dzi_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=emimage.models.get_dzi_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="emimage",
            name="file",
            field=models.FileField(upload_to=emimage.models.get_em_image_upload_path),
        ),
    ]
