# Generated by Django 5.0.6 on 2024-06-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emimage", "0003_remove_emimage_converted_file_emimage_dzi_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emimage",
            name="pixel_size_nm",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
